channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.0.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
